<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Visual reproduction of the 268 SIMRS Sahabat menus observed 2026-08-21.
 * Live hrefs point at existing teaching screens; other items are visual shells only.
 */
final class SimrsSahabatMenuCatalog
{
    /**
     * @return array<string, list<array{slug: string, label: string, vendor_route: string, status: string, href: string}>>
     */
    public static function menusByCategory(): array
    {
        $categories = [
            'pendaftaran' => [
                [
                    'slug' => 'pendaftaran-rawatinap',
                    'label' => 'Rawat Inap',
                    'vendor_route' => '/pendaftaran/rawatinap',
                    'status' => 'live',
                    'href' => '/pendaftaran/rawat-inap',
                ],
                [
                    'slug' => 'pendaftaran-ugd',
                    'label' => 'IGD',
                    'vendor_route' => '/pendaftaran/ugd',
                    'status' => 'live',
                    'href' => '/pendaftaran/igd',
                ],
                [
                    'slug' => 'pendaftaran-rawatjalan',
                    'label' => 'Rawat Jalan',
                    'vendor_route' => '/pendaftaran/rawatjalan',
                    'status' => 'live',
                    'href' => '/pendaftaran/rawat-jalan',
                ],
                [
                    'slug' => 'simrs-information-rawatinap',
                    'label' => 'Display Admisi',
                    'vendor_route' => '/simrs/information/rawatinap',
                    'status' => 'visual',
                    'href' => '/modul/pendaftaran/simrs-information-rawatinap',
                ],
                [
                    'slug' => 'pendaftaranv2-rawatjalanv2',
                    'label' => 'Rawat Jalan v2',
                    'vendor_route' => '/pendaftaranv2/rawatjalanv2',
                    'status' => 'consolidated',
                    'href' => '/modul/pendaftaran/pendaftaranv2-rawatjalanv2',
                ],
            ],
            'pemeriksaan' => [
                [
                    'slug' => 'pemeriksaan-assesmen',
                    'label' => 'Assesmen',
                    'vendor_route' => '/pemeriksaan/assesmen',
                    'status' => 'consolidated',
                    'href' => '/modul/pemeriksaan/pemeriksaan-assesmen',
                ],
                [
                    'slug' => 'pemeriksaan-triage',
                    'label' => 'Triage',
                    'vendor_route' => '/pemeriksaan/triage',
                    'status' => 'live',
                    'href' => '/pemeriksaan/triage',
                ],
                [
                    'slug' => 'pemeriksaan-ugd',
                    'label' => 'IGD',
                    'vendor_route' => '/pemeriksaan/ugd',
                    'status' => 'live',
                    'href' => '/pemeriksaan/igd',
                ],
                [
                    'slug' => 'pemeriksaan-rawatjalan',
                    'label' => 'Rawat Jalan',
                    'vendor_route' => '/pemeriksaan/rawatjalan',
                    'status' => 'live',
                    'href' => '/pemeriksaan/rawat-jalan',
                ],
                [
                    'slug' => 'pemeriksaan-rawatinap',
                    'label' => 'Rawat Inap',
                    'vendor_route' => '/pemeriksaan/rawatinap',
                    'status' => 'live',
                    'href' => '/pemeriksaan/rawat-inap',
                ],
                [
                    'slug' => 'pemeriksaan-laboratorium',
                    'label' => 'Laboratorium',
                    'vendor_route' => '/pemeriksaan/laboratorium',
                    'status' => 'live',
                    'href' => '/pemeriksaan/laboratorium',
                ],
                [
                    'slug' => 'pemeriksaan-radiologi',
                    'label' => 'Radiologi',
                    'vendor_route' => '/pemeriksaan/radiologi',
                    'status' => 'live',
                    'href' => '/pemeriksaan/radiologi',
                ],
                [
                    'slug' => 'pemeriksaan-gizi',
                    'label' => 'Gizi',
                    'vendor_route' => '/pemeriksaan/gizi',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-gizi',
                ],
                [
                    'slug' => 'pemeriksaan-operasi',
                    'label' => 'Operasi',
                    'vendor_route' => '/pemeriksaan/operasi',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-operasi',
                ],
                [
                    'slug' => 'pemeriksaanv3-operasi',
                    'label' => 'Operasi v3',
                    'vendor_route' => '/pemeriksaanv3/operasi',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaanv3-operasi',
                ],
                [
                    'slug' => 'pemeriksaan-fisioterapi',
                    'label' => 'Rehabilitasi Medis',
                    'vendor_route' => '/pemeriksaan/fisioterapi',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-fisioterapi',
                ],
                [
                    'slug' => 'pemeriksaan-fisioterapi2',
                    'label' => 'Instalasi Rehabilitasi Medik 2',
                    'vendor_route' => '/pemeriksaan/fisioterapi2',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-fisioterapi2',
                ],
                [
                    'slug' => 'pemeriksaan-terapiwicara',
                    'label' => 'Terapi Wicara',
                    'vendor_route' => '/pemeriksaan/terapiwicara',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-terapiwicara',
                ],
                [
                    'slug' => 'pemeriksaan-okupasiterapi',
                    'label' => 'Okupasi Terapi',
                    'vendor_route' => '/pemeriksaan/okupasiterapi',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-okupasiterapi',
                ],
                [
                    'slug' => 'pemeriksaan-laboratoriumpa',
                    'label' => 'Lab PA',
                    'vendor_route' => '/pemeriksaan/laboratoriumpa',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-laboratoriumpa',
                ],
                [
                    'slug' => 'pemeriksaan-laboratoriummikro',
                    'label' => 'Lab Mikro',
                    'vendor_route' => '/pemeriksaan/laboratoriummikro',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-laboratoriummikro',
                ],
                [
                    'slug' => 'pemeriksaan-bankdarah',
                    'label' => 'Bank Darah',
                    'vendor_route' => '/pemeriksaan/bankdarah',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-bankdarah',
                ],
                [
                    'slug' => 'pemeriksaan-jenazah',
                    'label' => 'Jenazah',
                    'vendor_route' => '/pemeriksaan/jenazah',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-jenazah',
                ],
                [
                    'slug' => 'pemeriksaanv3-rawatinap',
                    'label' => 'Rawat Inap v2',
                    'vendor_route' => '/pemeriksaanv3/rawatinap',
                    'status' => 'consolidated',
                    'href' => '/modul/pemeriksaan/pemeriksaanv3-rawatinap',
                ],
                [
                    'slug' => 'pemeriksaan-ambulance',
                    'label' => 'Ambulance',
                    'vendor_route' => '/pemeriksaan/ambulance',
                    'status' => 'visual',
                    'href' => '/modul/pemeriksaan/pemeriksaan-ambulance',
                ],
            ],
            'rm' => [
                [
                    'slug' => 'rm-rawatjalan',
                    'label' => 'Rawat Jalan',
                    'vendor_route' => '/rm/rawatjalan',
                    'status' => 'live',
                    'href' => '/rm/rawat-jalan',
                ],
                [
                    'slug' => 'rm-rawatinap',
                    'label' => 'Rawat Inap',
                    'vendor_route' => '/rm/rawatinap',
                    'status' => 'live',
                    'href' => '/rm/rawat-inap',
                ],
                [
                    'slug' => 'rm-monitorklaim',
                    'label' => 'Monitor Klaim',
                    'vendor_route' => '/rm/monitorklaim',
                    'status' => 'visual',
                    'href' => '/modul/rm/rm-monitorklaim',
                ],
                [
                    'slug' => 'rm-filing',
                    'label' => 'Filing',
                    'vendor_route' => '/rm/filing',
                    'status' => 'visual',
                    'href' => '/modul/rm/rm-filing',
                ],
                [
                    'slug' => 'rm-satusehatrajal',
                    'label' => 'SatuSehat RJ',
                    'vendor_route' => '/rm/satusehatrajal',
                    'status' => 'visual',
                    'href' => '/modul/rm/rm-satusehatrajal',
                ],
                [
                    'slug' => 'rm-ipp-rawatjalan',
                    'label' => 'EMR IPP RAWAT JALAN',
                    'vendor_route' => '/rm-ipp/rawatjalan',
                    'status' => 'consolidated',
                    'href' => '/rm/rawat-jalan',
                ],
                [
                    'slug' => 'rm-ipp-rawatinap',
                    'label' => 'EMR IPP RAWAT INAP',
                    'vendor_route' => '/rm-ipp/rawatinap',
                    'status' => 'consolidated',
                    'href' => '/rm/rawat-inap',
                ],
            ],
            'klaim' => [
                [
                    'slug' => 'klaim-rawatjalan',
                    'label' => 'Rawat Jalan',
                    'vendor_route' => '/klaim/rawatjalan',
                    'status' => 'visual',
                    'href' => '/modul/klaim/klaim-rawatjalan',
                ],
                [
                    'slug' => 'klaim-rawatinap',
                    'label' => 'Rawat Inap',
                    'vendor_route' => '/klaim/rawatinap',
                    'status' => 'visual',
                    'href' => '/modul/klaim/klaim-rawatinap',
                ],
                [
                    'slug' => 'klaim-rawatjalanidrg',
                    'label' => 'Rawat Jalan iDRG',
                    'vendor_route' => '/klaim/rawatjalanidrg',
                    'status' => 'visual',
                    'href' => '/modul/klaim/klaim-rawatjalanidrg',
                ],
                [
                    'slug' => 'klaim-rawatinapidrg',
                    'label' => 'Rawat Inap iDRG',
                    'vendor_route' => '/klaim/rawatinapidrg',
                    'status' => 'visual',
                    'href' => '/modul/klaim/klaim-rawatinapidrg',
                ],
                [
                    'slug' => 'klaim-rawatinapplafon',
                    'label' => 'Perk Plafon RI',
                    'vendor_route' => '/klaim/rawatinapplafon',
                    'status' => 'visual',
                    'href' => '/modul/klaim/klaim-rawatinapplafon',
                ],
                [
                    'slug' => 'klaim-monitorklaim',
                    'label' => 'Monitor Klaim',
                    'vendor_route' => '/klaim/monitorklaim',
                    'status' => 'visual',
                    'href' => '/modul/klaim/klaim-monitorklaim',
                ],
            ],
            'laporan' => [
                [
                    'slug' => 'statistik-sepuluhbesarrajal',
                    'label' => '10 Besar Penyakit Rajal',
                    'vendor_route' => '/statistik/sepuluhbesarrajal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-sepuluhbesarrajal',
                ],
                [
                    'slug' => 'statistik-sepuluhbesarranap',
                    'label' => '10 Besar Penyakit Ranap',
                    'vendor_route' => '/statistik/sepuluhbesarranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-sepuluhbesarranap',
                ],
                [
                    'slug' => 'statistik-sepuluhbesartindakanrajal',
                    'label' => '10 Tindakan Rajal',
                    'vendor_route' => '/statistik/sepuluhbesartindakanrajal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-sepuluhbesartindakanrajal',
                ],
                [
                    'slug' => 'statistik-sepuluhbesartindakanranap',
                    'label' => '10 Tindakan Ranap',
                    'vendor_route' => '/statistik/sepuluhbesartindakanranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-sepuluhbesartindakanranap',
                ],
                [
                    'slug' => 'statistik-pasien',
                    'label' => 'Pasien',
                    'vendor_route' => '/statistik/pasien',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-pasien',
                ],
                [
                    'slug' => 'statistik-kunjunganri',
                    'label' => 'Kunjungan RI',
                    'vendor_route' => '/statistik/kunjunganri',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-kunjunganri',
                ],
                [
                    'slug' => 'statistik-kunjungan',
                    'label' => 'Kunjungan RJ',
                    'vendor_route' => '/statistik/kunjungan',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-kunjungan',
                ],
                [
                    'slug' => 'statistik-trend',
                    'label' => 'Trend',
                    'vendor_route' => '/statistik/trend',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-trend',
                ],
                [
                    'slug' => 'statistik-monitoringresep',
                    'label' => 'Monitor Resep',
                    'vendor_route' => '/statistik/monitoringresep',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-monitoringresep',
                ],
                [
                    'slug' => 'statistik-waktu',
                    'label' => 'Waktu',
                    'vendor_route' => '/statistik/waktu',
                    'status' => 'visual',
                    'href' => '/modul/laporan/statistik-waktu',
                ],
                [
                    'slug' => 'laporan-kunjunganterakhir',
                    'label' => 'Kunjungan Terakhir',
                    'vendor_route' => '/laporan/kunjunganterakhir',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kunjunganterakhir',
                ],
                [
                    'slug' => 'laporan-registerlab',
                    'label' => 'Register Lab',
                    'vendor_route' => '/laporan/registerlab',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerlab',
                ],
                [
                    'slug' => 'laporan-registerigd',
                    'label' => 'Register IGD',
                    'vendor_route' => '/laporan/registerigd',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerigd',
                ],
                [
                    'slug' => 'laporan-registerradiologi',
                    'label' => 'Register Radiologi',
                    'vendor_route' => '/laporan/registerradiologi',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerradiologi',
                ],
                [
                    'slug' => 'laporan-registercancer',
                    'label' => 'Register Cancer',
                    'vendor_route' => '/laporan/registercancer',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registercancer',
                ],
                [
                    'slug' => 'laporan-registerrajal',
                    'label' => 'Register Rawat Jalan',
                    'vendor_route' => '/laporan/registerrajal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerrajal',
                ],
                [
                    'slug' => 'laporan-registerranap',
                    'label' => 'Register Rawat Inap',
                    'vendor_route' => '/laporan/registerranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerranap',
                ],
                [
                    'slug' => 'laporan-registeroperasi',
                    'label' => 'Register IBS',
                    'vendor_route' => '/laporan/registeroperasi',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registeroperasi',
                ],
                [
                    'slug' => 'laporan-registerpendaftaran',
                    'label' => 'Register Pendaftaran',
                    'vendor_route' => '/laporan/registerpendaftaran',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerpendaftaran',
                ],
                [
                    'slug' => 'laporan-rekapjhp',
                    'label' => 'Rekap JHP',
                    'vendor_route' => '/laporan/rekapjhp',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-rekapjhp',
                ],
                [
                    'slug' => 'laporan-w2',
                    'label' => 'W2',
                    'vendor_route' => '/laporan/w2',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-w2',
                ],
                [
                    'slug' => 'laporan-analisiskuantitatifranap',
                    'label' => 'A. Kuantitatif Ranap',
                    'vendor_route' => '/laporan/analisiskuantitatifranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-analisiskuantitatifranap',
                ],
                [
                    'slug' => 'laporan-masukranap',
                    'label' => 'Px Masuk Ranap',
                    'vendor_route' => '/laporan/masukranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-masukranap',
                ],
                [
                    'slug' => 'laporan-pindahranap',
                    'label' => 'Px Pindah Ranap',
                    'vendor_route' => '/laporan/pindahranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-pindahranap',
                ],
                [
                    'slug' => 'laporan-pulangranap',
                    'label' => 'Px Pulang',
                    'vendor_route' => '/laporan/pulangranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-pulangranap',
                ],
                [
                    'slug' => 'laporan-ptm',
                    'label' => 'PTM RAJAL',
                    'vendor_route' => '/laporan/ptm',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-ptm',
                ],
                [
                    'slug' => 'laporan-ptmv2',
                    'label' => 'PTM RAJAL V2',
                    'vendor_route' => '/laporan/Ptmv2',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-ptmv2',
                ],
                [
                    'slug' => 'laporan-ptmranap',
                    'label' => 'PTM RANAP',
                    'vendor_route' => '/laporan/ptmranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-ptmranap',
                ],
                [
                    'slug' => 'laporan-ptmranapv2',
                    'label' => 'PTM RANAP V2',
                    'vendor_route' => '/laporan/Ptmranapv2',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-ptmranapv2',
                ],
                [
                    'slug' => 'laporan-analisiskuantitatifrajal',
                    'label' => 'A. Kuantitatif Rajal',
                    'vendor_route' => '/laporan/analisiskuantitatifrajal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-analisiskuantitatifrajal',
                ],
                [
                    'slug' => 'laporan-analisiskuantitatifrajalrekap',
                    'label' => 'Rekap A.K. Rajal',
                    'vendor_route' => '/laporan/analisiskuantitatifrajalrekap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-analisiskuantitatifrajalrekap',
                ],
                [
                    'slug' => 'laporan-analisiskuantitatifranaprekap',
                    'label' => 'Rekap A.K. Ranap',
                    'vendor_route' => '/laporan/analisiskuantitatifranaprekap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-analisiskuantitatifranaprekap',
                ],
                [
                    'slug' => 'laporan-evaluasiketerlambatan',
                    'label' => 'Evaluasi Keterlambatan',
                    'vendor_route' => '/laporan/evaluasiketerlambatan',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-evaluasiketerlambatan',
                ],
                [
                    'slug' => 'laporan-rekapevaluasiketerlambatan',
                    'label' => 'Rekap Evaluasi Keterlambatan',
                    'vendor_route' => '/laporan/rekapevaluasiketerlambatan',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-rekapevaluasiketerlambatan',
                ],
                [
                    'slug' => 'laporan-kelengkapancatatanperawat',
                    'label' => 'K. Catatan Perawat',
                    'vendor_route' => '/laporan/kelengkapancatatanperawat',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kelengkapancatatanperawat',
                ],
                [
                    'slug' => 'laporan-kelengkapanresumeaskep',
                    'label' => 'K. Resume ASKEP',
                    'vendor_route' => '/laporan/kelengkapanresumeaskep',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kelengkapanresumeaskep',
                ],
                [
                    'slug' => 'laporan-kelengkapanrekammedis',
                    'label' => 'K. Rekam Medis',
                    'vendor_route' => '/laporan/kelengkapanrekammedis',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kelengkapanrekammedis',
                ],
                [
                    'slug' => 'laporan-perujuk',
                    'label' => 'Perujuk',
                    'vendor_route' => '/laporan/perujuk',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-perujuk',
                ],
                [
                    'slug' => 'laporan-imunisasi',
                    'label' => 'Imunisasi',
                    'vendor_route' => '/laporan/imunisasi',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-imunisasi',
                ],
                [
                    'slug' => 'laporan-kematian',
                    'label' => 'Kematian',
                    'vendor_route' => '/laporan/kematian',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kematian',
                ],
                [
                    'slug' => 'laporan-kematianaskes',
                    'label' => 'Kematian ASKES',
                    'vendor_route' => '/laporan/kematianaskes',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kematianaskes',
                ],
                [
                    'slug' => 'laporan-masihdirawat',
                    'label' => 'Masih Dirawat',
                    'vendor_route' => '/laporan/masihdirawat',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-masihdirawat',
                ],
                [
                    'slug' => 'laporan-kematianexternal',
                    'label' => 'Kematian External',
                    'vendor_route' => '/laporan/kematianexternal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-kematianexternal',
                ],
                [
                    'slug' => 'laporan-imunisasiranap',
                    'label' => 'Imunisasi Ranap',
                    'vendor_route' => '/laporan/imunisasiranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-imunisasiranap',
                ],
                [
                    'slug' => 'laporan-datacarabayar',
                    'label' => 'DATA CARA BAYAR',
                    'vendor_route' => '/laporan/datacarabayar',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-datacarabayar',
                ],
                [
                    'slug' => 'laporan-rekaphais',
                    'label' => 'Rekap HAI\'s',
                    'vendor_route' => '/laporan/rekaphais',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-rekaphais',
                ],
                [
                    'slug' => 'laporan-rekaphais2',
                    'label' => 'Rekap HAI\'s 2',
                    'vendor_route' => '/laporan/rekaphais2',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-rekaphais2',
                ],
                [
                    'slug' => 'laporan-registerinsiden',
                    'label' => 'Register Insiden',
                    'vendor_route' => '/laporan/registerinsiden',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerinsiden',
                ],
                [
                    'slug' => 'laporan-registerhais',
                    'label' => 'Register HAI\'s',
                    'vendor_route' => '/laporan/registerhais',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerhais',
                ],
                [
                    'slug' => 'laporan-sebaranpasien',
                    'label' => 'Sebaran Pasien',
                    'vendor_route' => '/laporan/sebaranpasien',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-sebaranpasien',
                ],
                [
                    'slug' => 'laporan-pulangranapdirujuk',
                    'label' => 'Px Dirujuk',
                    'vendor_route' => '/laporan/pulangranapdirujuk',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-pulangranapdirujuk',
                ],
                [
                    'slug' => 'laporan-rekapdirujuk',
                    'label' => 'Rekap Dirujuk',
                    'vendor_route' => '/laporan/rekapdirujuk',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-rekapdirujuk',
                ],
                [
                    'slug' => 'laporan-registerfiling',
                    'label' => 'Register Filing',
                    'vendor_route' => '/laporan/registerfiling',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-registerfiling',
                ],
                [
                    'slug' => 'laporan-rekapispa',
                    'label' => 'Rekap ISPA',
                    'vendor_route' => '/laporan/rekapispa',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-rekapispa',
                ],
                [
                    'slug' => 'laporan-ekincppt',
                    'label' => 'eKin CPPT',
                    'vendor_route' => '/laporan/ekincppt',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporan-ekincppt',
                ],
                [
                    'slug' => 'indeks-penyakitrajal',
                    'label' => 'Penyakit Rawat Jalan',
                    'vendor_route' => '/indeks/penyakitrajal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/indeks-penyakitrajal',
                ],
                [
                    'slug' => 'indeks-dokterrajal',
                    'label' => 'Dokter RJ',
                    'vendor_route' => '/indeks/dokterrajal',
                    'status' => 'visual',
                    'href' => '/modul/laporan/indeks-dokterrajal',
                ],
                [
                    'slug' => 'indeks-penyakitranap',
                    'label' => 'Penyakit Rawat Inap',
                    'vendor_route' => '/indeks/penyakitranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/indeks-penyakitranap',
                ],
                [
                    'slug' => 'indeks-tindakanrawatjalan',
                    'label' => 'Tindakan RJ',
                    'vendor_route' => '/indeks/tindakanrawatjalan',
                    'status' => 'visual',
                    'href' => '/modul/laporan/indeks-tindakanrawatjalan',
                ],
                [
                    'slug' => 'indeks-dokterranap',
                    'label' => 'Dokter RI',
                    'vendor_route' => '/indeks/dokterranap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/indeks-dokterranap',
                ],
                [
                    'slug' => 'indeks-tindakanrawatinap',
                    'label' => 'Tindakan RI',
                    'vendor_route' => '/indeks/tindakanrawatinap',
                    'status' => 'visual',
                    'href' => '/modul/laporan/indeks-tindakanrawatinap',
                ],
                [
                    'slug' => 'rl-rl31',
                    'label' => 'RL 3.1',
                    'vendor_route' => '/rl/rl31',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl31',
                ],
                [
                    'slug' => 'rl-rl32',
                    'label' => 'RL 3.2',
                    'vendor_route' => '/rl/rl32',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl32',
                ],
                [
                    'slug' => 'rl-rl33',
                    'label' => 'RL 3.3',
                    'vendor_route' => '/rl/rl33',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl33',
                ],
                [
                    'slug' => 'rl-rl34',
                    'label' => 'RL 3.4',
                    'vendor_route' => '/rl/rl34',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl34',
                ],
                [
                    'slug' => 'rl-rl35',
                    'label' => 'RL 3.5',
                    'vendor_route' => '/rl/rl35',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl35',
                ],
                [
                    'slug' => 'rl-rl36',
                    'label' => 'RL 3.6',
                    'vendor_route' => '/rl/rl36',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl36',
                ],
                [
                    'slug' => 'rl-rl37',
                    'label' => 'RL 3.7',
                    'vendor_route' => '/rl/rl37',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl37',
                ],
                [
                    'slug' => 'rl-rl38',
                    'label' => 'RL 3.8',
                    'vendor_route' => '/rl/rl38',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl38',
                ],
                [
                    'slug' => 'rl-rl39',
                    'label' => 'RL 3.9',
                    'vendor_route' => '/rl/rl39',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl39',
                ],
                [
                    'slug' => 'rl-rl311',
                    'label' => 'RL 3.11',
                    'vendor_route' => '/rl/rl311',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl311',
                ],
                [
                    'slug' => 'rl-rl310',
                    'label' => 'RL 3.10',
                    'vendor_route' => '/rl/rl310',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl310',
                ],
                [
                    'slug' => 'rl-rl312',
                    'label' => 'RL 3.12',
                    'vendor_route' => '/rl/rl312',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl312',
                ],
                [
                    'slug' => 'rl-rl313',
                    'label' => 'RL 3.13',
                    'vendor_route' => '/rl/rl313',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl313',
                ],
                [
                    'slug' => 'rl-rl314',
                    'label' => 'RL 3.14',
                    'vendor_route' => '/rl/rl314',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl314',
                ],
                [
                    'slug' => 'rl-rl315',
                    'label' => 'RL 3.15',
                    'vendor_route' => '/rl/rl315',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl315',
                ],
                [
                    'slug' => 'rl-rl316',
                    'label' => 'RL 3.16',
                    'vendor_route' => '/rl/rl316',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl316',
                ],
                [
                    'slug' => 'rl-rl317',
                    'label' => 'RL 3.17',
                    'vendor_route' => '/rl/rl317',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl317',
                ],
                [
                    'slug' => 'rl-rl318',
                    'label' => 'RL 3.18',
                    'vendor_route' => '/rl/rl318',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl318',
                ],
                [
                    'slug' => 'rl-rl319',
                    'label' => 'RL 3.19',
                    'vendor_route' => '/rl/rl319',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl319',
                ],
                [
                    'slug' => 'rl-rl41',
                    'label' => 'RL 4.1',
                    'vendor_route' => '/rl/rl41',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl41',
                ],
                [
                    'slug' => 'rl-rl42',
                    'label' => 'RL 4.2',
                    'vendor_route' => '/rl/rl42',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl42',
                ],
                [
                    'slug' => 'rl-rl43',
                    'label' => 'RL 4.3',
                    'vendor_route' => '/rl/rl43',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl43',
                ],
                [
                    'slug' => 'rl-rl51',
                    'label' => 'RL 5.1',
                    'vendor_route' => '/rl/rl51',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl51',
                ],
                [
                    'slug' => 'rl-rl52',
                    'label' => 'RL 5.2',
                    'vendor_route' => '/rl/rl52',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl52',
                ],
                [
                    'slug' => 'rl-rl53',
                    'label' => 'RL 5.3',
                    'vendor_route' => '/rl/rl53',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl53',
                ],
                [
                    'slug' => 'rl-rl4a',
                    'label' => 'RL 4A',
                    'vendor_route' => '/rl/rl4a',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl4a',
                ],
                [
                    'slug' => 'rl-rl4b',
                    'label' => 'RL 4B',
                    'vendor_route' => '/rl/rl4b',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl4b',
                ],
                [
                    'slug' => 'rl-rl4asebab',
                    'label' => 'RL4A Sebab',
                    'vendor_route' => '/rl/rl4asebab',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl4asebab',
                ],
                [
                    'slug' => 'rl-rl4bsebab',
                    'label' => 'RL4B Sebab',
                    'vendor_route' => '/rl/rl4bsebab',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl4bsebab',
                ],
                [
                    'slug' => 'rl-rl54',
                    'label' => 'RL 5.4',
                    'vendor_route' => '/rl/rl54',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-rl54',
                ],
                [
                    'slug' => 'rl-stprsrj',
                    'label' => 'STP-RS-RJ',
                    'vendor_route' => '/rl/stprsrj',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-stprsrj',
                ],
                [
                    'slug' => 'rl-stprsri',
                    'label' => 'STP-RS-RI',
                    'vendor_route' => '/rl/stprsri',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-stprsri',
                ],
                [
                    'slug' => 'rl-stprsri2',
                    'label' => 'STPRS-RI2',
                    'vendor_route' => '/rl/stprsri2',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-stprsri2',
                ],
                [
                    'slug' => 'rl-stprsrj2',
                    'label' => 'STPRS-RJ2',
                    'vendor_route' => '/rl/stprsrj2',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rl-stprsrj2',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perhari',
                    'label' => 'Per Hari',
                    'vendor_route' => '/rekapitulasirawatjalan/perhari',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perhari',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perbulan',
                    'label' => 'Per Bulan',
                    'vendor_route' => '/rekapitulasirawatjalan/perbulan',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perbulan',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perpoli',
                    'label' => 'Per Poliklinik',
                    'vendor_route' => '/rekapitulasirawatjalan/perpoli',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perpoli',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perdokter',
                    'label' => 'Per Dokter',
                    'vendor_route' => '/rekapitulasirawatjalan/perdokter',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perdokter',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perdokterbarulama',
                    'label' => 'Per Dokter Baru-Lama',
                    'vendor_route' => '/rekapitulasirawatjalan/perdokterbarulama',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perdokterbarulama',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-doados',
                    'label' => 'Pasien DOA-DOS',
                    'vendor_route' => '/rekapitulasirawatjalan/doados',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-doados',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-rujukkeluar',
                    'label' => 'Pasien Dirujuk Keluar',
                    'vendor_route' => '/rekapitulasirawatjalan/rujukkeluar',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-rujukkeluar',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-lakalantas',
                    'label' => 'Lakalantas',
                    'vendor_route' => '/rekapitulasirawatjalan/lakalantas',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-lakalantas',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perdokterbarulamaumum',
                    'label' => 'Per Dokter Umum',
                    'vendor_route' => '/rekapitulasirawatjalan/perdokterbarulamaumum',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perdokterbarulamaumum',
                ],
                [
                    'slug' => 'rekapitulasirawatjalan-perdokterbarulamaigd',
                    'label' => 'Per Dokter IGD',
                    'vendor_route' => '/rekapitulasirawatjalan/perdokterbarulamaigd',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatjalan-perdokterbarulamaigd',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-perbulan',
                    'label' => 'Per Bulan',
                    'vendor_route' => '/rekapitulasirawatinap/perbulan',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-perbulan',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-perruang',
                    'label' => 'Per Ruang',
                    'vendor_route' => '/rekapitulasirawatinap/perruang',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-perruang',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-perkelas',
                    'label' => 'Per Kelas',
                    'vendor_route' => '/rekapitulasirawatinap/perkelas',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-perkelas',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-perspesialis',
                    'label' => 'Per Spesialis',
                    'vendor_route' => '/rekapitulasirawatinap/perspesialis',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-perspesialis',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-perdokter',
                    'label' => 'Per Dokter',
                    'vendor_route' => '/rekapitulasirawatinap/perdokter',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-perdokter',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-dokterpulangaps',
                    'label' => 'Dokter APS',
                    'vendor_route' => '/rekapitulasirawatinap/dokterpulangaps',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-dokterpulangaps',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-indikasipulang',
                    'label' => 'Indikasi Pulang Per Kelas',
                    'vendor_route' => '/rekapitulasirawatinap/indikasipulang',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-indikasipulang',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-indikasipulangperruang',
                    'label' => 'Indikasi Pulang Per Ruang',
                    'vendor_route' => '/rekapitulasirawatinap/indikasipulangperruang',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-indikasipulangperruang',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-sebabaps',
                    'label' => 'Sebab Pulang APS',
                    'vendor_route' => '/rekapitulasirawatinap/sebabaps',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-sebabaps',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-kematian',
                    'label' => 'Kematian',
                    'vendor_route' => '/rekapitulasirawatinap/kematian',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-kematian',
                ],
                [
                    'slug' => 'rekapitulasirawatinap-statuspasiendirawat',
                    'label' => 'Status Pasien Dirawat',
                    'vendor_route' => '/rekapitulasirawatinap/statuspasiendirawat',
                    'status' => 'visual',
                    'href' => '/modul/laporan/rekapitulasirawatinap-statuspasiendirawat',
                ],
                [
                    'slug' => 'laporanfarmasi-rekapmonitor',
                    'label' => 'Rekap Monitor Resep',
                    'vendor_route' => '/laporanfarmasi/rekapmonitor',
                    'status' => 'visual',
                    'href' => '/modul/laporan/laporanfarmasi-rekapmonitor',
                ],
            ],
            'bpjs' => [
                [
                    'slug' => 'bpjs-rawatjalan',
                    'label' => 'Rawat Jalan',
                    'vendor_route' => '/bpjs/rawatjalan',
                    'status' => 'visual',
                    'href' => '/modul/bpjs/bpjs-rawatjalan',
                ],
                [
                    'slug' => 'bpjs-rawatinap',
                    'label' => 'Rawat Inap',
                    'vendor_route' => '/bpjs/rawatinap',
                    'status' => 'visual',
                    'href' => '/modul/bpjs/bpjs-rawatinap',
                ],
            ],
            'apotek' => [
                [
                    'slug' => 'apotek-igd-rawatjalan',
                    'label' => 'Apotek IGD',
                    'vendor_route' => '/apotek-igd/rawatjalan',
                    'status' => 'live',
                    'href' => '/apotek/resep',
                ],
                [
                    'slug' => 'apotek-rawatjalan',
                    'label' => 'Apotek Rawat Jalan',
                    'vendor_route' => '/apotek/rawatjalan',
                    'status' => 'live',
                    'href' => '/apotek/resep',
                ],
                [
                    'slug' => 'apotek-rawatinap',
                    'label' => 'Apotek Rawat Inap',
                    'vendor_route' => '/apotek/rawatinap',
                    'status' => 'live',
                    'href' => '/apotek/resep',
                ],
                [
                    'slug' => 'apotek-antrian',
                    'label' => 'Apotek Pasien Luar',
                    'vendor_route' => '/apotek/antrian',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-antrian',
                ],
                [
                    'slug' => 'apotek-distribusiobat',
                    'label' => 'Distribusi Obat',
                    'vendor_route' => '/apotek/distribusiobat',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-distribusiobat',
                ],
                [
                    'slug' => 'apotek-stockopname',
                    'label' => 'Stock Opname',
                    'vendor_route' => '/apotek/stockopname',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-stockopname',
                ],
                [
                    'slug' => 'apotek-laporanposisistock',
                    'label' => 'Laporan Posisi Stock',
                    'vendor_route' => '/apotek/laporanposisistock',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanposisistock',
                ],
                [
                    'slug' => 'apotek-laporandistribusi',
                    'label' => 'Laporan Distribusi Obat',
                    'vendor_route' => '/apotek/laporandistribusi',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporandistribusi',
                ],
                [
                    'slug' => 'apotek-laporanobatmasuk',
                    'label' => 'Laporan Obat Masuk',
                    'vendor_route' => '/apotek/laporanobatmasuk',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanobatmasuk',
                ],
                [
                    'slug' => 'apotek-laporanpemakaian',
                    'label' => 'Laporan Pemakaian Obat',
                    'vendor_route' => '/apotek/laporanpemakaian',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanpemakaian',
                ],
                [
                    'slug' => 'apotek-laporanpengeluaranrajal',
                    'label' => 'Pengeluaran Rajal',
                    'vendor_route' => '/apotek/laporanpengeluaranrajal',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanpengeluaranrajal',
                ],
                [
                    'slug' => 'apotek-laporanpengeluaranluar',
                    'label' => 'Pengeluaran Luar',
                    'vendor_route' => '/apotek/laporanpengeluaranluar',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanpengeluaranluar',
                ],
                [
                    'slug' => 'apotek-laporanpengeluaranranap',
                    'label' => 'Pengeluaran Ranap',
                    'vendor_route' => '/apotek/laporanpengeluaranranap',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanpengeluaranranap',
                ],
                [
                    'slug' => 'apotek-returbagian',
                    'label' => 'Retur Bagian',
                    'vendor_route' => '/apotek/returbagian',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-returbagian',
                ],
                [
                    'slug' => 'apotek-riwayatresep',
                    'label' => 'Riwayat Resep',
                    'vendor_route' => '/apotek/riwayatresep',
                    'status' => 'live',
                    'href' => '/apotek/riwayat',
                ],
                [
                    'slug' => 'apotek-trolirj',
                    'label' => 'Trolley RJ',
                    'vendor_route' => '/apotek/trolirj',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-trolirj',
                ],
                [
                    'slug' => 'apotek-troliri',
                    'label' => 'Trolley RI',
                    'vendor_route' => '/apotek/troliri',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-troliri',
                ],
                [
                    'slug' => 'apotek-laporanretur',
                    'label' => 'Laporan Retur Px',
                    'vendor_route' => '/apotek/laporanretur',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanretur',
                ],
                [
                    'slug' => 'apotek-laporanpengeluaran',
                    'label' => 'Pengeluaran',
                    'vendor_route' => '/apotek/laporanpengeluaran',
                    'status' => 'visual',
                    'href' => '/modul/apotek/apotek-laporanpengeluaran',
                ],
                [
                    'slug' => 'apotek-kartustock',
                    'label' => 'Kartu Stock',
                    'vendor_route' => '/apotek/kartustock',
                    'status' => 'live',
                    'href' => '/apotek/kartu-stok',
                ],
            ],
            'gf' => [
                [
                    'slug' => 'gudangfarmasi-obat',
                    'label' => 'Obat',
                    'vendor_route' => '/gudangfarmasi/obat',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-obat',
                ],
                [
                    'slug' => 'gudangfarmasi-obatmasuk',
                    'label' => 'Obat Masuk',
                    'vendor_route' => '/gudangfarmasi/obatmasuk',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-obatmasuk',
                ],
                [
                    'slug' => 'gudangfarmasi-distribusiobat',
                    'label' => 'Distribusi Obat',
                    'vendor_route' => '/gudangfarmasi/distribusiobat',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-distribusiobat',
                ],
                [
                    'slug' => 'gudangfarmasi-stockopname',
                    'label' => 'Stock Opname',
                    'vendor_route' => '/gudangfarmasi/stockopname',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-stockopname',
                ],
                [
                    'slug' => 'gudangfarmasi-retursupplier',
                    'label' => 'Retur Supplier',
                    'vendor_route' => '/gudangfarmasi/retursupplier',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-retursupplier',
                ],
                [
                    'slug' => 'gudangfarmasi-returbagian',
                    'label' => 'Retur Bagian',
                    'vendor_route' => '/gudangfarmasi/returbagian',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-returbagian',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanposisistock',
                    'label' => 'Laporan Posisi Stock',
                    'vendor_route' => '/gudangfarmasi/laporanposisistock',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanposisistock',
                ],
                [
                    'slug' => 'gudangfarmasi-laporandistribusi',
                    'label' => 'Laporan Distribusi Obat',
                    'vendor_route' => '/gudangfarmasi/laporandistribusi',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporandistribusi',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanobatmasuk',
                    'label' => 'Laporan Obat Masuk',
                    'vendor_route' => '/gudangfarmasi/laporanobatmasuk',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanobatmasuk',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanperpetual',
                    'label' => 'Laporan Perpetual',
                    'vendor_route' => '/gudangfarmasi/laporanperpetual',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanperpetual',
                ],
                [
                    'slug' => 'gudangfarmasi-kartustock',
                    'label' => 'Kartu Stock',
                    'vendor_route' => '/gudangfarmasi/kartustock',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-kartustock',
                ],
                [
                    'slug' => 'gudangfarmasi-obatmasuk2',
                    'label' => 'Obat Masuk 2',
                    'vendor_route' => '/gudangfarmasi/obatmasuk2',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-obatmasuk2',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanobated',
                    'label' => 'Obat ED',
                    'vendor_route' => '/gudangfarmasi/laporanobated',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanobated',
                ],
                [
                    'slug' => 'gudangfarmasi-stockedit',
                    'label' => 'Edit Transaksi',
                    'vendor_route' => '/gudangfarmasi/stockedit',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-stockedit',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanstockopname',
                    'label' => 'Laporan StockOpname',
                    'vendor_route' => '/gudangfarmasi/laporanstockopname',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanstockopname',
                ],
                [
                    'slug' => 'gudangfarmasi-distribusiobatantardepo',
                    'label' => 'Distribusi Antar Depo',
                    'vendor_route' => '/gudangfarmasi/distribusiobatantardepo',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-distribusiobatantardepo',
                ],
                [
                    'slug' => 'gudangfarmasi-pemesananobat',
                    'label' => 'Po/Pemesanan Obat',
                    'vendor_route' => '/gudangfarmasi/pemesananobat',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-pemesananobat',
                ],
                [
                    'slug' => 'gudangfarmasi-bufferstockobat-laporan',
                    'label' => 'Laporan Buffer Stok Obat',
                    'vendor_route' => '/gudangfarmasi/bufferstockobat/laporan',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-bufferstockobat-laporan',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanperpetualperobat',
                    'label' => 'Laporan Perpetual Per Obat',
                    'vendor_route' => '/gudangfarmasi/laporanperpetualperobat',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanperpetualperobat',
                ],
                [
                    'slug' => 'gudangfarmasi-laporanperpetualperobat-2',
                    'label' => 'Perpetual Per Obat',
                    'vendor_route' => '/gudangfarmasi/laporanperpetualperobat',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-laporanperpetualperobat-2',
                ],
                [
                    'slug' => 'gudangfarmasi-bufferstockobat',
                    'label' => 'Buffer Stock Obat',
                    'vendor_route' => '/gudangfarmasi/bufferstockobat',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-bufferstockobat',
                ],
                [
                    'slug' => 'gudangfarmasi-bloodstocks',
                    'label' => 'Blood Stocks',
                    'vendor_route' => '/gudangfarmasi/bloodstocks',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-bloodstocks',
                ],
                [
                    'slug' => 'gudangfarmasi-initiatestockopname',
                    'label' => 'Stock Opname Awal',
                    'vendor_route' => '/gudangfarmasi/initiatestockopname',
                    'status' => 'visual',
                    'href' => '/modul/gf/gudangfarmasi-initiatestockopname',
                ],
            ],
            'kasir' => [
                [
                    'slug' => 'keuangan-rawatjalan',
                    'label' => 'Rawat Jalan',
                    'vendor_route' => '/keuangan/rawatjalan',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-rawatjalan',
                ],
                [
                    'slug' => 'keuangan-rawatinap',
                    'label' => 'Rawat Inap',
                    'vendor_route' => '/keuangan/rawatinap',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-rawatinap',
                ],
                [
                    'slug' => 'keuangan-lain',
                    'label' => 'Transaksi Lain',
                    'vendor_route' => '/keuangan/lain',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-lain',
                ],
                [
                    'slug' => 'keuangan-laporandetailrajal',
                    'label' => 'Detail Rajal',
                    'vendor_route' => '/keuangan/laporandetailrajal',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-laporandetailrajal',
                ],
                [
                    'slug' => 'keuangan-laporandetailranap',
                    'label' => 'Detail Ranap',
                    'vendor_route' => '/keuangan/laporandetailranap',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-laporandetailranap',
                ],
                [
                    'slug' => 'keuangan-pendapatan',
                    'label' => 'Pendapatan',
                    'vendor_route' => '/keuangan/pendapatan',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatan',
                ],
                [
                    'slug' => 'keuangan-pendapatanranap',
                    'label' => 'Pendapatan Ranap',
                    'vendor_route' => '/keuangan/pendapatanranap',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatanranap',
                ],
                [
                    'slug' => 'keuangan-pendapatanrajal',
                    'label' => 'Pendapatan Rajal',
                    'vendor_route' => '/keuangan/pendapatanrajal',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatanrajal',
                ],
                [
                    'slug' => 'keuangan-pendapatanigd',
                    'label' => 'Pendapatan IGD',
                    'vendor_route' => '/keuangan/pendapatanigd',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatanigd',
                ],
                [
                    'slug' => 'keuangan-jm',
                    'label' => 'Jasa Medis',
                    'vendor_route' => '/keuangan/jm',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-jm',
                ],
                [
                    'slug' => 'keuangan-piutang',
                    'label' => 'Piutang',
                    'vendor_route' => '/keuangan/piutang',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-piutang',
                ],
                [
                    'slug' => 'keuangan-setoran',
                    'label' => 'Setoran',
                    'vendor_route' => '/keuangan/setoran',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-setoran',
                ],
                [
                    'slug' => 'keuangan-pendapatanlain',
                    'label' => 'Pendapatan Lain',
                    'vendor_route' => '/keuangan/pendapatanlain',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatanlain',
                ],
                [
                    'slug' => 'keuangan-pendapatanunit',
                    'label' => 'PENDAPATAN UNIT',
                    'vendor_route' => '/keuangan/pendapatanunit',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatanunit',
                ],
                [
                    'slug' => 'keuangan-setoranterima',
                    'label' => 'TERIMA SETORAN',
                    'vendor_route' => '/keuangan/setoranterima',
                    'status' => 'live',
                    'href' => '/kasir/batch-penerimaan-kas',
                ],
                [
                    'slug' => 'keuangan-pendapatantindakan',
                    'label' => 'Pendapatan Tindakan',
                    'vendor_route' => '/keuangan/pendapatantindakan',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-pendapatantindakan',
                ],
                [
                    'slug' => 'keuangan-jurnal',
                    'label' => 'Jurnal Otomatis',
                    'vendor_route' => '/keuangan/jurnal',
                    'status' => 'visual',
                    'href' => '/modul/kasir/keuangan-jurnal',
                ],
                [
                    'slug' => 'keuangan-tagihan',
                    'label' => 'Laporan Tagihan',
                    'vendor_route' => '/keuangan/tagihan',
                    'status' => 'live',
                    'href' => '/kasir/tagihan',
                ],
                [
                    'slug' => 'keuangan-tagihan-tagihan2',
                    'label' => 'Tagihan 2',
                    'vendor_route' => '/keuangan/tagihan/tagihan2',
                    'status' => 'live',
                    'href' => '/kasir/tagihan',
                ],
            ],
            'manajemen-data' => [
                [
                    'slug' => 'manajemendata-group',
                    'label' => 'Group',
                    'vendor_route' => '/manajemendata/group',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-group',
                ],
                [
                    'slug' => 'manajemendata-pengguna',
                    'label' => 'Pengguna',
                    'vendor_route' => '/manajemendata/pengguna',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-pengguna',
                ],
                [
                    'slug' => 'manajemendata-profile',
                    'label' => 'Settings',
                    'vendor_route' => '/manajemendata/profile',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-profile',
                ],
                [
                    'slug' => 'manajemendata-clinicalpathway',
                    'label' => 'Ref Clinical Pathway',
                    'vendor_route' => '/manajemendata/clinicalpathway',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-clinicalpathway',
                ],
                [
                    'slug' => 'manajemendata-menu',
                    'label' => 'Menu',
                    'vendor_route' => '/manajemendata/menu',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-menu',
                ],
                [
                    'slug' => 'manajemendata-paramedic',
                    'label' => 'Staff Medis',
                    'vendor_route' => '/manajemendata/paramedic',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-paramedic',
                ],
                [
                    'slug' => 'manajemendata-targetrajal',
                    'label' => 'Target Rajal',
                    'vendor_route' => '/manajemendata/targetrajal',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-targetrajal',
                ],
                [
                    'slug' => 'manajemendata-tandatangan',
                    'label' => 'Template Tanda Tangan',
                    'vendor_route' => '/manajemendata/tandatangan',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-tandatangan',
                ],
                [
                    'slug' => 'manajemendata-tt',
                    'label' => 'Bangsal',
                    'vendor_route' => '/manajemendata/tt',
                    'status' => 'live',
                    'href' => '/manajemen-data/bangsal',
                ],
                [
                    'slug' => 'manajemendata-paymenttypes',
                    'label' => 'Data Cara Bayar',
                    'vendor_route' => '/manajemendata/paymenttypes',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-paymenttypes',
                ],
                [
                    'slug' => 'manajemendata-tarif',
                    'label' => 'Tarif',
                    'vendor_route' => '/manajemendata/tarif',
                    'status' => 'live',
                    'href' => '/manajemen-data/tarif-komponen-biaya',
                ],
                [
                    'slug' => 'manajemendata-printer',
                    'label' => 'Printer & Service',
                    'vendor_route' => '/manajemendata/printer',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-printer',
                ],
                [
                    'slug' => 'manajemendata-clinic',
                    'label' => 'Unit & Poliklinik',
                    'vendor_route' => '/manajemendata/clinic',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-clinic',
                ],
                [
                    'slug' => 'manajemendata-pemeriksaanlab',
                    'label' => 'Pemeriksaan Lab',
                    'vendor_route' => '/manajemendata/pemeriksaanlab',
                    'status' => 'live',
                    'href' => '/manajemen-data/laboratorium',
                ],
                [
                    'slug' => 'manajemendata-pemeriksaanradiologi',
                    'label' => 'Pemeriksaan Radiologi',
                    'vendor_route' => '/manajemendata/pemeriksaanradiologi',
                    'status' => 'live',
                    'href' => '/manajemen-data/radiologi',
                ],
                [
                    'slug' => 'manajemendata-bank',
                    'label' => 'Bank',
                    'vendor_route' => '/manajemendata/bank',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-bank',
                ],
                [
                    'slug' => 'manajemendata-supplier',
                    'label' => 'Supplier',
                    'vendor_route' => '/manajemendata/supplier',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-supplier',
                ],
                [
                    'slug' => 'manajemendata-komponenbiayagroup',
                    'label' => 'Group Komponen Biaya',
                    'vendor_route' => '/manajemendata/komponenbiayagroup',
                    'status' => 'live',
                    'href' => '/manajemen-data/tarif-komponen-biaya',
                ],
                [
                    'slug' => 'manajemendata-komponenbiaya',
                    'label' => 'Komponen Biaya',
                    'vendor_route' => '/manajemendata/komponenbiaya',
                    'status' => 'live',
                    'href' => '/manajemen-data/tarif-komponen-biaya',
                ],
                [
                    'slug' => 'manajemendata-diskonapotek',
                    'label' => 'Diskon Apotek',
                    'vendor_route' => '/manajemendata/diskonapotek',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-diskonapotek',
                ],
                [
                    'slug' => 'manajemendata-kelengkapanranap',
                    'label' => 'Kelengkapan RI',
                    'vendor_route' => '/manajemendata/kelengkapanranap',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-kelengkapanranap',
                ],
                [
                    'slug' => 'manajemendata-job',
                    'label' => 'Pekerjaan',
                    'vendor_route' => '/manajemendata/job',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-job',
                ],
                [
                    'slug' => 'manajemendata-education',
                    'label' => 'Pendidikan',
                    'vendor_route' => '/manajemendata/education',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-education',
                ],
                [
                    'slug' => 'manajemendata-suku',
                    'label' => 'Suku',
                    'vendor_route' => '/manajemendata/suku',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-suku',
                ],
                [
                    'slug' => 'manajemendata-bahasa',
                    'label' => 'Bahasa',
                    'vendor_route' => '/manajemendata/bahasa',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-bahasa',
                ],
                [
                    'slug' => 'manajemendata-instrumen',
                    'label' => 'Instrumen',
                    'vendor_route' => '/manajemendata/instrumen',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-instrumen',
                ],
                [
                    'slug' => 'manajemendata-emrdocument',
                    'label' => 'DOC EMR',
                    'vendor_route' => '/manajemendata/emrdocument',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-emrdocument',
                ],
                [
                    'slug' => 'manajemendata-emrdocument2',
                    'label' => 'DOC EMR 2',
                    'vendor_route' => '/manajemendata/emrdocument2',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-emrdocument2',
                ],
                [
                    'slug' => 'manajemendata-monitoringresep',
                    'label' => 'DATA MONITOR FARMASI',
                    'vendor_route' => '/manajemendata/monitoringresep',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-monitoringresep',
                ],
                [
                    'slug' => 'manajemendata-depo',
                    'label' => 'Depo',
                    'vendor_route' => '/manajemendata/depo',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-depo',
                ],
                [
                    'slug' => 'manajemendata-penyakitmenular',
                    'label' => 'Penyakit Menular',
                    'vendor_route' => '/manajemendata/penyakitmenular',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-penyakitmenular',
                ],
                [
                    'slug' => 'manajemendata-patient',
                    'label' => 'Pasien',
                    'vendor_route' => '/manajemendata/patient',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-patient',
                ],
                [
                    'slug' => 'manajemendata-kelas',
                    'label' => 'Kelas',
                    'vendor_route' => '/manajemendata/kelas',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-kelas',
                ],
                [
                    'slug' => 'manajemendata-diagnosiskeperawatan',
                    'label' => 'Diag Keperawatan',
                    'vendor_route' => '/manajemendata/diagnosiskeperawatan',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-diagnosiskeperawatan',
                ],
                [
                    'slug' => 'manajemendata-w2',
                    'label' => 'W2',
                    'vendor_route' => '/manajemendata/W2',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-w2',
                ],
                [
                    'slug' => 'manajemendata-odontogram',
                    'label' => 'Odontogram',
                    'vendor_route' => '/manajemendata/Odontogram',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-odontogram',
                ],
                [
                    'slug' => 'manajemendata-logsystem',
                    'label' => 'Log Activity',
                    'vendor_route' => '/manajemendata/logsystem',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-logsystem',
                ],
                [
                    'slug' => 'manajemendata-logesign',
                    'label' => 'LOG ESIGN',
                    'vendor_route' => '/manajemendata/logesign',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-logesign',
                ],
                [
                    'slug' => 'manajemendata-targetpendapatan',
                    'label' => 'Target Pendapatan',
                    'vendor_route' => '/manajemendata/targetpendapatan',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-targetpendapatan',
                ],
                [
                    'slug' => 'manajemendata-logbridging',
                    'label' => 'Log Bridging',
                    'vendor_route' => '/manajemendata/logbridging',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-logbridging',
                ],
                [
                    'slug' => 'manajemendata-paramedicibs',
                    'label' => 'Group IBS',
                    'vendor_route' => '/manajemendata/paramedicibs',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-paramedicibs',
                ],
                [
                    'slug' => 'manajemendata-paketobat',
                    'label' => 'Paket Obat',
                    'vendor_route' => '/manajemendata/paketobat',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-paketobat',
                ],
                [
                    'slug' => 'manajemendata-specimen',
                    'label' => 'Specimen',
                    'vendor_route' => '/manajemendata/specimen',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-specimen',
                ],
                [
                    'slug' => 'manajemendata-logsatusehatdebug',
                    'label' => 'Logsatset',
                    'vendor_route' => '/manajemendata/logsatusehatdebug',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-logsatusehatdebug',
                ],
                [
                    'slug' => 'manajemendata-logsatusehatridebug',
                    'label' => 'logsatsetri',
                    'vendor_route' => '/manajemendata/logsatusehatridebug',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-logsatusehatridebug',
                ],
                [
                    'slug' => 'manajemendata-alatmedis',
                    'label' => 'Alat Medis',
                    'vendor_route' => '/manajemendata/alatmedis',
                    'status' => 'visual',
                    'href' => '/modul/manajemen-data/manajemendata-alatmedis',
                ],
            ],
            'iot' => [
                [
                    'slug' => 'iot-temperature',
                    'label' => 'Temperature',
                    'vendor_route' => '/iot/temperature',
                    'status' => 'visual',
                    'href' => '/modul/iot/iot-temperature',
                ],
            ],
            'farmasi-ibs' => [
                [
                    'slug' => 'farmasiibs-rawatjalan',
                    'label' => 'IBS',
                    'vendor_route' => '/farmasiibs/rawatjalan',
                    'status' => 'visual',
                    'href' => '/modul/farmasi-ibs/farmasiibs-rawatjalan',
                ],
            ],
            'help' => [
                [
                    'slug' => 'webroot-help-manual-pdf',
                    'label' => 'Manual Book',
                    'vendor_route' => '/webroot/help/manual.pdf',
                    'status' => 'visual',
                    'href' => '/modul/help/webroot-help-manual-pdf',
                ],
            ],
        ];

        foreach ($categories as &$menus) {
            foreach ($menus as &$menu) {
                $menu['label'] = ScreenVocabulary::label($menu['label']);
            }
            unset($menu);
        }
        unset($menus);

        return $categories;
    }

    /**
     * @return list<array{slug: string, label: string, vendor_route: string, status: string, href: string}>
     */
    public static function menusFor(string $category): array
    {
        return self::menusByCategory()[$category] ?? [];
    }

    /**
     * @return array{slug: string, label: string, vendor_route: string, status: string, href: string}|null
     */
    public static function find(string $category, string $item): ?array
    {
        foreach (self::menusFor($category) as $menu) {
            if ($menu['slug'] === $item) {
                return $menu;
            }
        }

        return null;
    }
}
