<?php

declare(strict_types=1);

/**
 * Serve build-time Vite assets from the PHP function bundle.
 *
 * The vercel-php runtime can include files generated by Composer's `vercel`
 * script in a function bundle, but those files are not public automatically.
 */
$requestedAsset = rawurldecode((string) ($_GET['asset'] ?? ''));
$requestedAsset = str_replace('\\', '/', $requestedAsset);

if ($requestedAsset === ''
    || str_contains($requestedAsset, "\0")
    || str_starts_with($requestedAsset, '/')
    || preg_match('#(^|/)\.\.(/|$)#', $requestedAsset) === 1) {
    http_response_code(404);
    exit;
}

$publicRoot = realpath(__DIR__.'/../public');
$assetPath = realpath(__DIR__.'/../public/'.$requestedAsset);

if ($publicRoot === false
    || $assetPath === false
    || ! str_starts_with($assetPath, $publicRoot.DIRECTORY_SEPARATOR)
    || ! is_file($assetPath)) {
    http_response_code(404);
    exit;
}

$mimeTypes = [
    'css' => 'text/css; charset=utf-8',
    'gif' => 'image/gif',
    'ico' => 'image/x-icon',
    'jpeg' => 'image/jpeg',
    'jpg' => 'image/jpeg',
    'js' => 'text/javascript; charset=utf-8',
    'json' => 'application/json; charset=utf-8',
    'map' => 'application/json; charset=utf-8',
    'png' => 'image/png',
    'svg' => 'image/svg+xml; charset=utf-8',
    'txt' => 'text/plain; charset=utf-8',
    'webp' => 'image/webp',
    'woff' => 'font/woff',
    'woff2' => 'font/woff2',
];
$extension = strtolower(pathinfo($assetPath, PATHINFO_EXTENSION));

header('Content-Type: '.($mimeTypes[$extension] ?? 'application/octet-stream'));
header('Content-Length: '.(string) filesize($assetPath));
header('X-Content-Type-Options: nosniff');

if (str_starts_with($requestedAsset, 'build/assets/')) {
    header('Cache-Control: public, max-age=31536000, immutable');
} else {
    header('Cache-Control: public, max-age=3600');
}

readfile($assetPath);
